# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\Actionfall\resource\UI\newtab.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1212, 792)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 90, 1151, 621))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(110, 110))
        self.tabWidget.setBaseSize(QtCore.QSize(22, 22))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(18)
        self.tabWidget.setFont(font)
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setTabletTracking(False)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.tabWidget.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(48, 48))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.mailbutton = QtWidgets.QPushButton(self.tab)
        self.mailbutton.setGeometry(QtCore.QRect(240, 370, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mailbutton.setFont(font)
        self.mailbutton.setStyleSheet("QPushButton{background-color:green;border:none;color:#ffffff;}\n"
"QPushButton:hover{background-color:#333333;}\n"
"QPushButton:pressed{background-color:#663333;}\n"
"qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0 rgba(255, 255, 255, 255), stop:0.373979 rgba(255, 255, 255, 255), stop:0.373991 rgba(33, 30, 255, 255), stop:0.624018 rgba(33, 30, 255, 255), stop:0.624043 rgba(255, 0, 0, 255), stop:1 rgba(255, 0, 0, 255))")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../sundry/icons/button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("../sundry/icons/button1.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("../sundry/icons/button1.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.mailbutton.setIcon(icon)
        self.mailbutton.setIconSize(QtCore.QSize(32, 32))
        self.mailbutton.setObjectName("mailbutton")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(400, 10, 391, 331))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("sundry/alarmbg.jpg"))
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.sirenbutton = QtWidgets.QPushButton(self.tab)
        self.sirenbutton.setGeometry(QtCore.QRect(240, 450, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sirenbutton.setFont(font)
        self.sirenbutton.setStyleSheet("QPushButton{background-color:green;border:none;color:#ffffff;}\n"
"QPushButton:hover{background-color:#333333;}\n"
"QPushButton:pressed{background-color:#999999;}\n"
"qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.077, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147))\n"
"selection-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.077, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));")
        self.sirenbutton.setIcon(icon)
        self.sirenbutton.setIconSize(QtCore.QSize(32, 32))
        self.sirenbutton.setObjectName("sirenbutton")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(420, 370, 41, 41))
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setAutoFillBackground(False)
        self.label_9.setText("")
        self.label_9.setTextFormat(QtCore.Qt.AutoText)
        self.label_9.setPixmap(QtGui.QPixmap("sundry/about1.png"))
        self.label_9.setScaledContents(False)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setWordWrap(False)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(420, 450, 41, 41))
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setAutoFillBackground(False)
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("sundry/about1.png"))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(470, 360, 471, 61))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setTextFormat(QtCore.Qt.PlainText)
        self.label_11.setScaledContents(True)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(470, 440, 471, 61))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setTextFormat(QtCore.Qt.PlainText)
        self.label_12.setScaledContents(True)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("sundry/page3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("sundry/page3_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.tab, icon1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(0, 10, 581, 421))
        self.label_3.setMouseTracking(False)
        self.label_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("sundry/app2.png"))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(130, 450, 131, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(12, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("sundry/res2.png"))
        self.label_8.setScaledContents(False)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(670, 460, 461, 61))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setAutoFillBackground(False)
        self.label_15.setTextFormat(QtCore.Qt.RichText)
        self.label_15.setScaledContents(True)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(590, 450, 72, 71))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("sundry/about.png"))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(590, 10, 542, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(10, -1, -1, 5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.videobutton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.videobutton.setFont(font)
        self.videobutton.setStyleSheet("QRadioButton::indicator:unchecked {\n"
"        background:white;border-radius:7px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"        background:#6DDF6D;border-radius:7px;\n"
"}\n"
"")
        self.videobutton.setObjectName("videobutton")
        self.verticalLayout_2.addWidget(self.videobutton)
        self.selectvideo = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.selectvideo.setFont(font)
        self.selectvideo.setStyleSheet("QPushButton{background-color:green;border:none;color:#ffffff;}\n"
"QPushButton:hover{background-color:#333333;}\n"
"QPushButton:pressed{background-color:#663333;}\n"
"qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0 rgba(255, 255, 255, 255), stop:0.373979 rgba(255, 255, 255, 255), stop:0.373991 rgba(33, 30, 255, 255), stop:0.624018 rgba(33, 30, 255, 255), stop:0.624043 rgba(255, 0, 0, 255), stop:1 rgba(255, 0, 0, 255))")
        self.selectvideo.setObjectName("selectvideo")
        self.verticalLayout_2.addWidget(self.selectvideo)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.camerabutton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.camerabutton.setFont(font)
        self.camerabutton.setStyleSheet("QRadioButton::indicator:unchecked {\n"
"        background:white;border-radius:7px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"        background:#6DDF6D;border-radius:7px;\n"
"}\n"
"")
        self.camerabutton.setObjectName("camerabutton")
        self.horizontalLayout_3.addWidget(self.camerabutton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setLineWidth(3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.checkfpsbtn = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.checkfpsbtn.setFont(font)
        self.checkfpsbtn.setStyleSheet("QCheckBox::indicator:unchecked {\n"
"        background:#F76677;border-radius:7px;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"        background:#6DDF6D;border-radius:7px;\n"
"}\n"
"\n"
"")
        self.checkfpsbtn.setTristate(False)
        self.checkfpsbtn.setObjectName("checkfpsbtn")
        self.verticalLayout.addWidget(self.checkfpsbtn)
        self.checkprobabilitybtn = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.checkprobabilitybtn.setFont(font)
        self.checkprobabilitybtn.setStyleSheet("QCheckBox::indicator:unchecked {\n"
"        background:#F76677;border-radius:7px;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"        background:#6DDF6D;border-radius:7px;\n"
"}\n"
"")
        self.checkprobabilitybtn.setObjectName("checkprobabilitybtn")
        self.verticalLayout.addWidget(self.checkprobabilitybtn)
        self.checknormalitybtn = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.checknormalitybtn.setFont(font)
        self.checknormalitybtn.setStyleSheet("QCheckBox::indicator:unchecked {\n"
"        background:#F76677;border-radius:7px;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"        background:#6DDF6D;border-radius:7px;\n"
"}\n"
"")
        self.checknormalitybtn.setObjectName("checknormalitybtn")
        self.verticalLayout.addWidget(self.checknormalitybtn)
        self.checkskeletonbtn = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.checkskeletonbtn.setFont(font)
        self.checkskeletonbtn.setStyleSheet("QCheckBox::indicator:unchecked {\n"
"        background:#F76677;border-radius:7px;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"        background:#6DDF6D;border-radius:7px;\n"
"}\n"
"")
        self.checkskeletonbtn.setObjectName("checkskeletonbtn")
        self.verticalLayout.addWidget(self.checkskeletonbtn)
        self.predictbutton = QtWidgets.QPushButton(self.tab_2)
        self.predictbutton.setGeometry(QtCore.QRect(290, 450, 171, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.predictbutton.setFont(font)
        self.predictbutton.setStyleSheet("QPushButton{background-color:green;border:none;color:#ffffff;}\n"
"QPushButton:hover{background-color:#333333;}\n"
"QPushButton:pressed{background-color:#663333;}\n"
"qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0 rgba(255, 255, 255, 255), stop:0.373979 rgba(255, 255, 255, 255), stop:0.373991 rgba(33, 30, 255, 255), stop:0.624018 rgba(33, 30, 255, 255), stop:0.624043 rgba(255, 0, 0, 255), stop:1 rgba(255, 0, 0, 255))")
        self.predictbutton.setObjectName("predictbutton")
        self.horizontalLayoutWidget.raise_()
        self.label_3.raise_()
        self.label_15.raise_()
        self.label_6.raise_()
        self.verticalLayoutWidget.raise_()
        self.predictbutton.raise_()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("sundry/tab2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("sundry/tab.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.tab_2, icon2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_5)
        self.textBrowser.setGeometry(QtCore.QRect(270, 50, 781, 221))
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser.setObjectName("textBrowser")
        self.searchinfobtn = QtWidgets.QPushButton(self.tab_5)
        self.searchinfobtn.setGeometry(QtCore.QRect(70, 70, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.searchinfobtn.setFont(font)
        self.searchinfobtn.setStyleSheet("QPushButton{background-color:green;border:none;color:#ffffff;}\n"
"QPushButton:hover{background-color:#333333;}\n"
"QPushButton:pressed{background-color:#663333;}\n"
"qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0 rgba(255, 255, 255, 255), stop:0.373979 rgba(255, 255, 255, 255), stop:0.373991 rgba(33, 30, 255, 255), stop:0.624018 rgba(33, 30, 255, 255), stop:0.624043 rgba(255, 0, 0, 255), stop:1 rgba(255, 0, 0, 255))")
        self.searchinfobtn.setObjectName("searchinfobtn")
        self.line_3 = QtWidgets.QFrame(self.tab_5)
        self.line_3.setGeometry(QtCore.QRect(10, 310, 1131, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.newpwdbtn = QtWidgets.QPushButton(self.tab_5)
        self.newpwdbtn.setGeometry(QtCore.QRect(500, 350, 93, 28))
        self.newpwdbtn.setStyleSheet("QPushButton{background-color:green;border:none;color:#ffffff;}\n"
"QPushButton:hover{background-color:#333333;}\n"
"QPushButton:pressed{background-color:#663333;}\n"
"qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0 rgba(255, 255, 255, 255), stop:0.373979 rgba(255, 255, 255, 255), stop:0.373991 rgba(33, 30, 255, 255), stop:0.624018 rgba(33, 30, 255, 255), stop:0.624043 rgba(255, 0, 0, 255), stop:1 rgba(255, 0, 0, 255))")
        self.newpwdbtn.setObjectName("newpwdbtn")
        self.newpwd_le = QtWidgets.QLineEdit(self.tab_5)
        self.newpwd_le.setGeometry(QtCore.QRect(200, 350, 261, 31))
        self.newpwd_le.setObjectName("newpwd_le")
        self.newmailbtn = QtWidgets.QPushButton(self.tab_5)
        self.newmailbtn.setGeometry(QtCore.QRect(500, 420, 93, 28))
        self.newmailbtn.setStyleSheet("QPushButton{background-color:green;border:none;color:#ffffff;}\n"
"QPushButton:hover{background-color:#333333;}\n"
"QPushButton:pressed{background-color:#663333;}\n"
"qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0 rgba(255, 255, 255, 255), stop:0.373979 rgba(255, 255, 255, 255), stop:0.373991 rgba(33, 30, 255, 255), stop:0.624018 rgba(33, 30, 255, 255), stop:0.624043 rgba(255, 0, 0, 255), stop:1 rgba(255, 0, 0, 255))")
        self.newmailbtn.setObjectName("newmailbtn")
        self.newphonebtn = QtWidgets.QPushButton(self.tab_5)
        self.newphonebtn.setGeometry(QtCore.QRect(500, 480, 93, 28))
        self.newphonebtn.setStyleSheet("QPushButton{background-color:green;border:none;color:#ffffff;}\n"
"QPushButton:hover{background-color:#333333;}\n"
"QPushButton:pressed{background-color:#663333;}\n"
"qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0 rgba(255, 255, 255, 255), stop:0.373979 rgba(255, 255, 255, 255), stop:0.373991 rgba(33, 30, 255, 255), stop:0.624018 rgba(33, 30, 255, 255), stop:0.624043 rgba(255, 0, 0, 255), stop:1 rgba(255, 0, 0, 255))")
        self.newphonebtn.setObjectName("newphonebtn")
        self.newmail_le = QtWidgets.QLineEdit(self.tab_5)
        self.newmail_le.setGeometry(QtCore.QRect(200, 420, 261, 31))
        self.newmail_le.setObjectName("newmail_le")
        self.newphone_le = QtWidgets.QLineEdit(self.tab_5)
        self.newphone_le.setGeometry(QtCore.QRect(200, 480, 261, 31))
        self.newphone_le.setObjectName("newphone_le")
        self.label_5 = QtWidgets.QLabel(self.tab_5)
        self.label_5.setGeometry(QtCore.QRect(790, 390, 201, 81))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.tab_5)
        self.label_4.setGeometry(QtCore.QRect(40, 150, 211, 91))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_13 = QtWidgets.QLabel(self.tab_5)
        self.label_13.setGeometry(QtCore.QRect(100, 350, 81, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_5)
        self.label_14.setGeometry(QtCore.QRect(100, 420, 81, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_16 = QtWidgets.QLabel(self.tab_5)
        self.label_16.setGeometry(QtCore.QRect(100, 480, 81, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab_5)
        self.label_17.setGeometry(QtCore.QRect(740, 400, 41, 51))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("sundry/about1.png"))
        self.label_17.setObjectName("label_17")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("sundry/train2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("sundry/train.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.tab_5, icon3, "")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 20, 1211, 81))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(24)
        font.setUnderline(False)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1212, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mailbutton.setText(_translate("MainWindow", "设置邮箱"))
        self.sirenbutton.setText(_translate("MainWindow", "设置警报"))
        self.label_11.setText(_translate("MainWindow", "点击输入邮箱，在检测到老人发生摔倒后发\n"
"送提醒到指定邮箱"))
        self.label_12.setText(_translate("MainWindow", "点击设置警报，在检测到老人发生摔倒后系\n"
"统会发出警报声"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "设置提醒"))
        self.label_7.setText(_translate("MainWindow", "正常"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">检测摄像头前老人的活动状态，请确保全身都可以被摄</span></p><p><span style=\" font-size:11pt;\">像头所采集到，运行前请调整上方设置</span></p></body></html>"))
        self.videobutton.setText(_translate("MainWindow", "检测指定视频"))
        self.selectvideo.setText(_translate("MainWindow", "选择视频"))
        self.camerabutton.setText(_translate("MainWindow", "监控摄像头"))
        self.checkfpsbtn.setText(_translate("MainWindow", "是否显示帧数与FPS"))
        self.checkprobabilitybtn.setText(_translate("MainWindow", "是否显示预测动作概率"))
        self.checknormalitybtn.setText(_translate("MainWindow", "是否显示非跌倒状态"))
        self.checkskeletonbtn.setText(_translate("MainWindow", "是否显示人物骨架"))
        self.predictbutton.setText(_translate("MainWindow", "点击开始"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "姿态预估"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.searchinfobtn.setText(_translate("MainWindow", "查看"))
        self.newpwdbtn.setText(_translate("MainWindow", "提交"))
        self.newmailbtn.setText(_translate("MainWindow", "提交"))
        self.newphonebtn.setText(_translate("MainWindow", "提交"))
        self.label_5.setText(_translate("MainWindow", "点击修改个人信息"))
        self.label_4.setText(_translate("MainWindow", "点击查看所有摔倒记录"))
        self.label_13.setText(_translate("MainWindow", "更换密码"))
        self.label_14.setText(_translate("MainWindow", "更换邮箱"))
        self.label_16.setText(_translate("MainWindow", "更换手机"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "个人信息"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">基于骨骼数据的摔倒监测系统</p></body></html>"))
